name = "worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "1fed5897e8e8d7fa525091234a77b5e4"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"
[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt"]